#if !canImport(ObjectiveC)
import XCTest

extension Matrix4Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Matrix4Tests = [
        ("testDeterminant", testDeterminant),
        ("testInitWithRotation", testInitWithRotation),
        ("testInitWithScale", testInitWithScale),
        ("testInitWithTranslation", testInitWithTranslation),
        ("testInverted", testInverted),
        ("testLookAt", testLookAt),
        ("testMultiplyByMatrix4", testMultiplyByMatrix4),
        ("testMultiplyByVector3", testMultiplyByVector3),
        ("testSubscript", testSubscript),
        ("testTransposed", testTransposed),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Matrix4Tests.__allTests__Matrix4Tests),
    ]
}
#endif
